DESCRIBE `LOGIN`;
DESCRIBE `USER`;
DESCRIBE `MATCH_OFFICIAL`;
DESCRIBE `PLAYER`;
DESCRIBE `PLAYER_ARCHIVE`;
DESCRIBE `TEAM`;
DESCRIBE `MATCH`;
DESCRIBE `GAME`;




SHOW FULL COLUMNS FROM `LOGIN`;
SHOW FULL COLUMNS FROM `USER`;
SHOW FULL COLUMNS FROM `MATCH_OFFICIAL`;
SHOW FULL COLUMNS FROM `PLAYER`;
SHOW FULL COLUMNS FROM `PLAYER_ARCHIVE`;
SHOW FULL COLUMNS FROM `TEAM`;
SHOW FULL COLUMNS FROM `MATCH`;
SHOW FULL COLUMNS FROM `GAME`;