DROP TABLE IF EXISTS `MATCH`;
DROP TABLE IF EXISTS `PLAYER_ARCHIVE`;
DROP TABLE IF EXISTS `GAME`;
DROP TABLE IF EXISTS `TEAM`;
DROP TABLE IF EXISTS `PLAYER`;
DROP TABLE IF EXISTS `MATCH_OFFICIAL`;
DROP TABLE IF EXISTS `LOGIN`;
DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER`(
	USER_ID INTEGER UNSIGNED AUTO_INCREMENT NOT NULL,
	USER_PICTURE VARCHAR(10) NOT NULL COMMENT "location of picture, within user_pics directory",
	USER_FNAME VARCHAR(100) NOT NULL,
	USER_LNAME VARCHAR(100) NOT NULL,
	USER_DOB DATE NOT NULL,
	USER_TYPE VARCHAR(14) DEFAULT "spectator" NOT NULL CHECK (USER_TYPE = "spectator" || USER_TYPE = "match_official" || USER_TYPE = "player") COMMENT "spectator, match_official player",
	PRIMARY KEY(USER_ID),
	INDEX (USER_ID)
)	AUTO_INCREMENT = 10000;

CREATE TABLE `TEAM`(
	TEAM_ID INTEGER UNSIGNED AUTO_INCREMENT NOT NULL,
	TEAM_NAME VARCHAR(250) NOT NULL,
	TEAM_LOGO VARCHAR(10) NOT NULL COMMENT "location of team logo, within team_pics directory",
	TEAM_FOUNDED DATE NOT NULL COMMENT "date team was founded",
	TEAM_PCOUNT INTEGER DEFAULT 0 NOT NULL COMMENT "total games team has played",
	TEAM_WINS INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	TEAM_LOSSES INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	TEAM_DRAWS INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	TEAM_G_FOR INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	TEAM_G_AGAINST INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	TEAM_G_DIFF INTEGER DEFAULT 0 NOT NULL,
	TEAM_G_WIN_RATE DOUBLE(3,2) DEFAULT 0 NOT NULL,
	USER_ID INTEGER UNSIGNED NOT NULL COMMENT "organizer",
	PRIMARY KEY (TEAM_ID),
	INDEX (TEAM_ID),
	FOREIGN KEY (USER_ID) REFERENCES `USER` (USER_ID),
	INDEX (USER_ID)
)	AUTO_INCREMENT = 90000;

CREATE TABLE `LOGIN`(
	USER_ID INTEGER UNSIGNED NOT NULL,
	LOGIN_UNAME VARCHAR(100) NOT NULL COMMENT "username",
	LOGIN_PASS TEXT NOT NULL COMMENT "login password",
	PRIMARY KEY (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES `USER`(USER_ID),
	INDEX (USER_ID)
);

CREATE TABLE `PLAYER`(
	USER_ID INTEGER UNSIGNED NOT NULL,
	PLAYER_FOOT CHAR(1) NOT NULL COMMENT "player's dominant foot",
	PLAYER_PCOUNT INTEGER DEFAULT 0 NOT NULL COMMENT "total number of games player has played",
	PLAYER_TWINS INTEGER DEFAULT 0 NOT NULL COMMENT "total wins with player",
	PLAYER_TDRAWS INTEGER DEFAULT 0 NOT NULL COMMENT "total draws with player",
	PLAYER_TLOSSES INTEGER DEFAULT 0 NOT NULL COMMENT "total losses with player",
	PLAYER_AVG_RATING DOUBLE(2,1) UNSIGNED CHECK (PLAYER_AVG_RATING >= 0 && PLAYER_AVG_RATING <= 5) COMMENT "total player average",
	PRIMARY KEY (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES `USER` (USER_ID),
	INDEX (USER_ID)
);

CREATE TABLE `MATCH_OFFICIAL`(
	USER_ID INTEGER UNSIGNED NOT NULL,
	MOFF_REFEREE BOOLEAN DEFAULT true NOT NULL COMMENT "is official a referee?",
	MOFF_ORGANNIZER BOOLEAN DEFAULT true NOT NULL COMMENT "is official a team creator/ match organizer?",
	PRIMARY KEY (USER_ID),
	FOREIGN KEY (USER_ID) REFERENCES `USER` (USER_ID),
	INDEX (USER_ID)
);

CREATE TABLE `GAME`(
	GAME_ID INTEGER UNSIGNED AUTO_INCREMENT NOT NULL,
	USER_ID INTEGER UNSIGNED NOT NULL COMMENT "referee",
	GAME_DATE DATE NOT NULL,
	GAME_TIME TIME NOT NULL,
	PRIMARY KEY (GAME_ID, USER_ID),
	INDEX (GAME_ID),
	FOREIGN KEY(USER_ID) REFERENCES `MATCH_OFFICIAL` (USER_ID),
	INDEX (USER_ID)
)	AUTO_INCREMENT = 1;

CREATE TABLE `MATCH`(
	GAME_ID INTEGER UNSIGNED NOT NULL,
	TEAM_ID INTEGER UNSIGNED NOT NULL,
	TEAM_SCORE INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	PRIMARY KEY (GAME_ID, TEAM_ID),
	FOREIGN KEY(GAME_ID) REFERENCES `GAME` (GAME_ID),
	INDEX (GAME_ID),
	FOREIGN KEY(TEAM_ID) REFERENCES `TEAM` (TEAM_ID),
	INDEX (TEAM_ID)	
);

CREATE TABLE `PLAYER_ARCHIVE`(
	GAME_ID INTEGER UNSIGNED NOT NULL,
	TEAM_ID INTEGER UNSIGNED NOT NULL,
	USER_ID INTEGER UNSIGNED NOT NULL COMMENT "player",
	PARC_POSITION VARCHAR(5) NOT NULL COMMENT "def att mid, and their variations",
	PARC_GOALS_SCORED INTEGER UNSIGNED DEFAULT 0 NOT NULL,
	PARC_CAPTAIN BOOLEAN DEFAULT false NOT NULL,
	PARC_RATING DOUBLE(2,1) UNSIGNED CHECK (PARC_RATING >= 0 && PARC_RATING <= 5) NOT NULL,
	PRIMARY KEY (GAME_ID, TEAM_ID, USER_ID),
	FOREIGN KEY(GAME_ID) REFERENCES `GAME` (GAME_ID),
	INDEX (GAME_ID),
	FOREIGN KEY(TEAM_ID) REFERENCES `TEAM` (TEAM_ID),
	INDEX (TEAM_ID),
	FOREIGN KEY(USER_ID) REFERENCES `PLAYER` (USER_ID),
	INDEX (USER_ID)
);


/*
DESCRIBE `USER`;
DESCRIBE `MATCH_OFFICIAL`;
DESCRIBE `PLAYER`;
DESCRIBE `PLAYER_ARCHIVE`;
DESCRIBE `TEAM`;
DESCRIBE `MATCH`;
DESCRIBE `GAME`;

SHOW FULL COLUMNS FROM `LOGIN`;
SHOW FULL COLUMNS FROM `USER`;
SHOW FULL COLUMNS FROM `MATCH_OFFICIAL`;
SHOW FULL COLUMNS FROM `PLAYER`;
SHOW FULL COLUMNS FROM `PLAYER_ARCHIVE`;
SHOW FULL COLUMNS FROM `TEAM`;
SHOW FULL COLUMNS FROM `MATCH`;
SHOW FULL COLUMNS FROM `GAME`;
*/